### ISSUE TITLE
Some videos show throw errors

### ISSUE THREAD

**Issue by jelly** [jelly/plugin.video.fosdem#3]
```
19:27:49.375 T:139906796799744   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object is not iterable
                                            Traceback (most recent call last):
                                              File "/home/jelle/.kodi/addons/plugin.video.fosdem/addon.py", line 153, in <module>
                                                plugin.run()
                                              File "/home/jelle/.kodi/addons/script.module.routing/lib/routing.py", line 115, in run
                                                self._dispatch(path)
                                              File "/home/jelle/.kodi/addons/script.module.routing/lib/routing.py", line 126, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/jelle/.kodi/addons/plugin.video.fosdem/addon.py", line 101, in show_room
                                                persons = [p.text for p in event.find('./persons/person')]
                                            TypeError: 'NoneType' object is not iterable
                                            -->End of Python script error report<--
```

**Comment by dagwieers** [comment]
This is already fixed with https://github.com/jelly/plugin.video.fosdem/commit/9625d225f9f920ddd2488d163d62fa7dfc039d7a
